import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "@/lib/generated/api-schema"; // generated by openapi-typescript
import store from "@/stores/store";
import { accessTokenAtom } from "@/stores/access-token";

const api = createClient<paths>({ baseUrl: "http://localhost:3000" });
const accessTokenInjectMiddleware = {
  async onRequest({ request }) {
    const accessToken = store.get(accessTokenAtom);
    if (accessToken) {
      request.headers.set("Authorization", "Bearer " + accessToken);
    }
    return request;
  },

  async onResponse({ response, request, options: _options }) {
    if (response.status === 401) {
      const response = await fetch(request.url, {
        ...request,
      });
      return response;
    } else if (response.status >= 400) {
      throw new Error(
        `Error happened, detail: ${(await response.json()).message}`,
      );
    }
    return response;
  },
} satisfies Middleware;

api.use(accessTokenInjectMiddleware);

export default api;
